#!/bin/sh
# shellcheck disable=SC2064
set -eu

# pve-nag-buster (v05) https://github.com/foundObjects/pve-nag-buster
# Copyright (C) 2019 /u/seaQueue (reddit.com/u/seaQueue)
#
# Removes Proxmox VE 6.x - 9.x license nags automatically after updates
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# ensure a predictable environment
PATH=/usr/sbin:/usr/bin:/sbin:/bin
\unalias -a

# installer main body:
_main() {
  # ensure $1 exists so 'set -u' doesn't error out
  { [ "$#" -eq "0" ] && set -- ""; } > /dev/null 2>&1

  case "$1" in
    "--emit")
      # call the emit_script() function to stdout and exit, use this to verify
      # that the base64 encoded script below isn't doing anything malicious
      # does not require root
      emit_script
      ;;
    "--uninstall")
      # uninstall, requires root
      assert_root
      _uninstall
      ;;
    "--install" | "--offline" | "")
      # install dpkg hooks, requires root
      assert_root
      _install "$@"
      ;;
    *)
      # unknown flags, print usage and exit
      _usage
      ;;
  esac
  exit 0
}

_uninstall() {
  set -x
  [ -f "/etc/apt/apt.conf.d/86pve-nags" ] &&
    rm -f "/etc/apt/apt.conf.d/86pve-nags"
  [ -f "/usr/share/pve-nag-buster.sh" ] &&
    rm -f "/usr/share/pve-nag-buster.sh"

  set +x
  echo ""
  echo "Script and dpkg hooks removed."
  echo "The following files were NOT removed (delete manually if desired):"
  echo "  /etc/apt/sources.list.d/pve-no-subscription.list"
  echo "  /etc/apt/sources.list.d/pve-no-subscription.sources"
  echo "  /etc/apt/sources.list.d/ceph-no-subscription.sources"
}

_install() {
  # create hooks and no-subscription repo list, install hook script, run once

  VERSION_CODENAME=''
  # shellcheck disable=SC1091
  . /etc/os-release
  if [ -n "$VERSION_CODENAME" ]; then
    RELEASE="$VERSION_CODENAME"
  else
    RELEASE=$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)
  fi

  # Detect PVE major version for format selection
  PVE_VERSION=""
  if command -v pveversion >/dev/null 2>&1; then
    PVE_VERSION=$(pveversion | sed -n 's/.*pve-manager\/\([0-9]*\)\..*/\1/p')
  fi

  # PVE 8+ uses deb822 .sources format, older uses .list
  if [ "${PVE_VERSION:-0}" -ge 8 ]; then
    echo "Creating PVE no-subscription repo (deb822 format for PVE $PVE_VERSION)..."
    cat <<- EOF > "/etc/apt/sources.list.d/pve-no-subscription.sources"
	# deb822 sources file generated by pve-nag-buster at $(date)
	# If pve-nag-buster is installed again this file will be overwritten

	Types: deb
	URIs: http://download.proxmox.com/debian/pve
	Suites: $RELEASE
	Components: pve-no-subscription
	Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
	EOF

    # Also create Ceph no-subscription repo for PVE 8+
    echo "Creating Ceph no-subscription repo..."
    cat <<- EOF > "/etc/apt/sources.list.d/ceph-no-subscription.sources"
	# deb822 sources file generated by pve-nag-buster at $(date)

	Types: deb
	URIs: http://download.proxmox.com/debian/ceph-reef
	Suites: $RELEASE
	Components: no-subscription
	Signed-By: /usr/share/keyrings/proxmox-archive-keyring.gpg
	EOF
  else
    echo "Creating PVE no-subscription repo list..."
    cat <<- EOF > "/etc/apt/sources.list.d/pve-no-subscription.list"
	# .list file automatically generated by pve-nag-buster at $(date)
	#
	# If pve-nag-buster is installed again this file will be overwritten
	#

	deb http://download.proxmox.com/debian/pve $RELEASE pve-no-subscription
	EOF
  fi

  # create dpkg pre/post install hooks for persistence
  echo "Creating dpkg hooks in /etc/apt/apt.conf.d ..."
  cat <<- 'EOF' > "/etc/apt/apt.conf.d/86pve-nags"
	DPkg::Pre-Install-Pkgs {
	    "while read -r pkg; do case $pkg in *proxmox-widget-toolkit* | *pve-manager*) touch /tmp/.pve-nag-buster && exit 0; esac done < /dev/stdin";
	};

	DPkg::Post-Invoke {
	    "[ -f /tmp/.pve-nag-buster ] && { /usr/share/pve-nag-buster.sh; rm -f /tmp/.pve-nag-buster; }; exit 0";
	};
	EOF

  # install the hook script
  temp=''
  if [ "$1" = "--offline" ]; then
    # packed script requested
    temp="$(mktemp)" && trap "rm -f $temp" EXIT
    emit_script > "$temp"
  elif [ -f "pve-nag-buster.sh" ]; then
    # local copy available
    temp="pve-nag-buster.sh"
  else
    # fetch from github
    echo "Fetching hook script from GitHub ..."
    tempd="$(mktemp -d)" &&
      trap "echo 'Cleaning up temporary files ...'; rm -f $tempd/*; rmdir $tempd" EXIT
    temp="$tempd/pve-nag-buster.sh"
    wget https://raw.githubusercontent.com/foundObjects/pve-nag-buster/master/pve-nag-buster.sh \
      -q --show-progress -O "$temp"
  fi
  echo "Installing hook script as /usr/share/pve-nag-buster.sh"
  install -o root -m 0550 "$temp" "/usr/share/pve-nag-buster.sh"

  echo "Running patch script"
  /usr/share/pve-nag-buster.sh

  return 0
}

# emit a stored copy of pve-nag-buster.sh offline -- this is intended to be used during
# offline provisioning where we don't have access to github or a full cloned copy of the
# project

# run 'install.sh --emit' to dump stored script to stdout

# Important: if you're not me you should probably decode this and read it to make sure I'm not doing
#            something malicious like mining dogecoin or stealing your valuable cat pictures

# pve-nag-buster.sh (v05) encoded below:

emit_script() {
  base64 -d << 'YEET' | unxz
/Td6WFoAAATm1rRGBMCuC/AbIQEWAAAAAAAAAJcY2RrgDe8Fpl0AEYhCRj30FjRzCg2PxTR1yCjB
uzjWosL5p6OYZBiP2QN5RhBheVvZiqGgks7Tx7yEh7wygYmq9xXEzlVB6EU0+qrg4fUqFseBgbPl
BJ1xgUE+/YONjj2KjzmkIR0FdHDrAuSRM6mbs2hBCzpknkX6+0dbPvQeadF82EemOtvXoZwrQRGE
EqEQLCf0DQCMXkDsLjgQr/Xbg3O/kwvySfTM0Ky0lsjqvA/YbaQfCd1jtz/pMAcOzEXGkEvsEkL2
f/oXUomST6x5rZqXKbhBoBqktMe54A+Us018NIQ+RykM0CVX1OdeOC78sQBp8AiYtqH8PqXr5jtN
A2x1R6WS9yJcwpopAxJdtZUJ3grjedzXaPIQlsNkrO+9pt6LwqJngPAKQHl5UGqOG+72OcxwL22e
08SHjqpc0Ypb4qzuwRc0DCWGTakVqwgPft4LOquAeuT2Ua2gtGZ7+gP73QDrLGzitePzT+snhs8G
BQmNv1fjjAzLo6Nv63Njhx+ti3tYJN3H7V38SIeOk3OVCBHLv0R7FwVEXvKeVhw7VFByzq2BsceS
ioLn6QyOCEFju4kWivye75kw3DCoOdkL+djG4TQmrQ9frkPwiQyaP9XHkAVTRDWyZZujFYE3mLTp
20dK4OcaElJv8w8ufJ/WZ4gh+lM4Nb5IAv6zFkp3zRF8rrmYzPeP5hJ3qVAP/0xuGycwRg9GSWlQ
X6yp99CpItuIkGzE79ge6TPyh282+hcBeWJAF/M7Vovm7CYd0EdGgR3AsQQc1Zi7c43V+ciF5nMT
D/1ykMhQdPbwggLA+zfNrObkPNwRZUuL/u7y+SdVZvOu4B7nGUlP+yyG0uQC8JIgYdr36qguhAZh
W9fOJeu8YqAoMVqQD8S64PUJciSheAaHJpiOtcymuct3JYAwGDO08e2rpGeySiL4lA0H91dAIop0
WIa6RNSEMrS+l7dUxNE1PxCfjdH5HcEiMcZdY+RZNvYoZWnVhyaSy8qS5mf2ci3xwa0uQUbaBWWq
W/oPxEfyETS0dEcGBHwUcgSnFpWQU4Am5d/2JlCe2CtwVrAO7VN0n4Gs1R/6fkRJ7fuWUdxdkSCf
LgkBS7BA8Gp1aQbZoqItxSpDk0tC+v/Al/rldg9dAxI9yFVp5uDlNeTlzUx/0idNbmYNZN0TUxbh
yxRCr9WDunBR0IrHN7hwSx5BdLNI3ND4wGkOzgjm3eTFevX1NxTvweZDEwMhNFDTA0twmxnag6iV
u4qwgPpH0gAvRy+JEGF4ER77woUmHmunLrFyG5nByFkpXXOpTwZGv2o+MhJ3q1KXtc9RmWwmq1An
UxjwafR8HPmLNhPTK5/Pk6WJPSnm3CQ30tXP4QBRVtvnIeE6EXSTEOtmYrLQdtaL9XYg7JdTGxZb
o5G4US/FcR5W3S/JARCWmjRmZ/R3X3Ob8tOKW/zN0mPC4Mfifxp1fuSr6Fk1YQiVnckJjDpS5bnW
jpyU101DTOJCFqYXsShOH3cs76Wjn8Z7Jm1Ve/zyZOAa9dAm8G8G+o8iUOvHKJ/ep/SIMPsKqSgW
bTnxuLwIkg9yhRXWWGfQtJEknqZkEDcn7cACNYZaEDYlGMho1HA/yWf5tb5Ygapp/QHaSvfWMZA1
+3QNLIuEVT4S3BPHBq0Ny5ahyoPt2OLsQJnZ5VDGj7gcyJaUuj7Ldpo4kc2TOtxFR5w+QVoah9Cm
BY3iXSN9YCRoevE4KctUZEjk5J96y1f5aGEvr0CYmeyihpAukvt6hgt71Rb3pfOOL9gUbbFd0qiT
wEd+FZVClFLq32AZswdczdPJoLoTPWeq9A+XMwS1mddrIZgjT+pOA46cNyhljpH1as66z7yJ/J9P
2o3nyBHW7UnsGEhraAqFcaJ6esfiee11CqxSvi0+cpXYhlz3Ot8NWaOqs38fZwQ5r1RWowp1d+64
KusUAAAAy+gd8diW3AgAAcoL8BsAACiC45KxxGf7AgAAAAAEWVo=
YEET
}

assert_root() { [ "$(id -u)" -eq '0' ] || { echo "This action requires root." && exit 1; }; }
_usage() { echo "Usage: $(basename "$0") (--emit|--offline|--uninstall)"; }

_main "$@"
